---
title: "Homework 1"
author: "Mengjiao Wu & Yaqi Dai"
date: "January 28, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Abstract


# 2. Introduction




# 3. Math Theory
Monte Carlo methods
equation
$$\Phi(t) = \int_{-\infty}^t{\frac{1}{\sqrt{2\pi}}}e^{-\frac{y^2}{2}}{\rm d}y$$



# 4. Code chunks




# 5. Table
Table containing true values and approximated values derived from Monte Carlo methods is shown as below: 
```{r echo=FALSE}
Result_Matrix <- matrix(data = NA,nrow=5,ncol=9)
t_set <- c(0,0.67,0.84,1.28,1.65,2.32,2.58,3.09,3.72)
Result_Matrix[2,] <- as.matrix(pnorm(t_set))
N_set <- c(100,1000,10000)
Result_Matrix[1,] <- t_set
i=3
for(N in N_set){
  j=1
  for(t in t_set){
    x <- rnorm(N, mean=0, sd=1)
    Indicator_variable <- as.numeric(x <= t)
    Fi_t = mean(Indicator_variable)
    Result_Matrix[i,j] <- Fi_t
    j=j+1
  }
  i=i+1
}
Result_Table <- t(Result_Matrix) 
colnames(Result_Table) <- c("**t value**", "**True value**", 
                            "**N=100**", "**N=1000**", 
                            "**N=10000**")
knitr::kable(
  Result_Table, digits = 4, align = c(rep('c', 5)), 
  caption = "True & approximated values for different Ns"
  )
```

# 6. Figures




# 7. Discussion and Conclusion



